#!/usr/bin/env bash
# gen-formula.sh — Generate Formula/edgeparse.rb from published GitHub Release assets.
#
# Usage:
#   scripts/gen-formula.sh <version> <output-file>
#
# The script downloads the macOS release tarballs, computes their SHA-256,
# and writes a ready-to-commit Homebrew formula.  The GitHub Release must
# already exist and the macOS assets must be published.
#
# Requires: curl, shasum
set -euo pipefail

VERSION="${1:-}"
OUTPUT="${2:-Formula/edgeparse.rb}"

if [[ -z "$VERSION" ]]; then
  echo "Usage: $0 <version> [output-file]" >&2
  exit 1
fi

BASE_URL="https://github.com/raphaelmansuy/edgeparse/releases/download/v${VERSION}"
ARM64_URL="${BASE_URL}/edgeparse-${VERSION}-aarch64-apple-darwin.tar.gz"
X64_URL="${BASE_URL}/edgeparse-${VERSION}-x86_64-apple-darwin.tar.gz"

# Helper: compute SHA256 from a local file (if it exists) or stream from URL.
sha256_of() {
  local url="$1"
  local filename
  filename="$(basename "$url")"
  # Try local release-dist directory first (available right after publish-cli)
  for candidate in \
      "target/release-dist/${filename}" \
      "$(dirname "$0")/../target/release-dist/${filename}"; do
    if [[ -f "$candidate" ]]; then
      shasum -a 256 "$candidate" | awk '{print $1}'
      return
    fi
  done
  # Fall back to downloading from GitHub Release
  curl -sL "$url" | shasum -a 256 | awk '{print $1}'
}

echo "  Computing SHA256 for aarch64-apple-darwin ..."
ARM64_SHA=$(sha256_of "$ARM64_URL")

echo "  Computing SHA256 for x86_64-apple-darwin ..."
X64_SHA=$(sha256_of "$X64_URL")

echo "  ARM64  SHA256: $ARM64_SHA"
echo "  x86_64 SHA256: $X64_SHA"

mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << FORMULA
# Auto-generated by \`make publish-brew\` — do not edit manually.
class Edgeparse < Formula
  desc "High-performance PDF-to-Markdown/JSON extraction engine (Rust)"
  homepage "https://github.com/raphaelmansuy/edgeparse"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${ARM64_URL}"
      sha256 "${ARM64_SHA}"
    end
    on_intel do
      url "${X64_URL}"
      sha256 "${X64_SHA}"
    end
  end

  def install
    bin.install "edgeparse"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/edgeparse --version")
  end
end
FORMULA

echo "  Formula written to: $OUTPUT"
